"""empty message

Revision ID: 2002df1d8576
Revises: 4ed8c9104f39
Create Date: 2018-03-23 09:24:05.463938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2002df1d8576'
down_revision = '4ed8c9104f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('img_dir', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'img_dir')
    # ### end Alembic commands ###
