"""empty message

Revision ID: 65f443661944
Revises: c90a18034d85
Create Date: 2018-03-26 10:20:24.487125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f443661944'
down_revision = 'c90a18034d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication_imgs', sa.Column('img_subtitle', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication_imgs', 'img_subtitle')
    # ### end Alembic commands ###
