"""update

Revision ID: 95baa444dbbd
Revises: b88b5428b920
Create Date: 2018-03-22 10:41:36.309680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95baa444dbbd'
down_revision = 'b88b5428b920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pub_authors',
    sa.Column('pub_id', sa.Integer(), nullable=True),
    sa.Column('auth_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auth_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['pub_id'], ['publications.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pub_authors')
    # ### end Alembic commands ###
