"""empty message

Revision ID: eace192c486c
Revises: 95baa444dbbd
Create Date: 2018-03-22 11:22:44.251108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eace192c486c'
down_revision = '95baa444dbbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_authors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_authors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pub_id', sa.INTEGER(), nullable=True),
    sa.Column('auth_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['auth_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['pub_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
